### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by 15762260991** [marciniega/spp3d_demo#1]

**Comment by marciniega** [comment]
Hi. It should work. Tray to train also with different rotations of your box. There is dependency there. The architecture allows different sizes but the weights are still sensible if rotated examples aren’t provided.


Enviado desde Yahoo Mail para iPhone


El miércoles, junio 21, 2023, 8:38 a.m., caiji ***@***.***> escribió:




Could you please tell me if the pyramid pooling you provided can be used for human action recognition? I have found that it does not work very well, but it is not clear why at the moment.

**Comment by 15762260991** [comment]
> Hi. It should work. Tray to train also with different rotations of your box. There is dependency there. The architecture allows different sizes but the weights are still sensible if rotated examples aren’t provided. Enviado desde Yahoo Mail para iPhone El miércoles, junio 21, 2023, 8:38 a.m., caiji ***@***.***> escribió: Could you please tell me if the pyramid pooling you provided can be used for human action recognition? I have found that it does not work very well, but it is not clear why at the moment. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from torchvision.models.video import mc3_18
from ptflops import get_model_complexity_info
from count_params import import_class, count_params

class MC3_SPP(nn.Module):
    def __init__(self, num_classes=10):
        super(MC3_SPP, self).__init__()

        self.mc3 = mc3_18(pretrained=False)
        
        self.mc3.pool = nn.Identity()
        self.mc3.fc = nn.Identity()
        self.mc3.avgpool = nn.Identity()
        
        self.pool3 = Spp3D([1, 2, 4], mode='avg')
        self.dropout1 = nn.Dropout3d(0.3)
        self.fc1 = nn.Linear(37376, 512) #32
        self.dropout2 = nn.Dropout3d(0.1)
        self.fc2 = nn.Linear(512, num_classes)


    def forward(self, x):
        features = self.mc3.stem(x)
        features = self.mc3.layer1(features)
        features = self.mc3.layer2(features)
        features = self.mc3.layer3(features)
        features = self.mc3.layer4(features)
        features = self.pool3(features)  # SPP max
        features = self.dropout1(features)
        features = torch.flatten(features, 1)  # Flatten tensor
        #print(features.shape)
        features = F.relu(self.fc1(features))  # First fully connected layer
        features = self.dropout2(features)
        features = self.fc2(features)
 

        return features


class Spp3D(nn.Module):
    """
    Args:
        levels (tuple): Length of side in the pooling results of each pyramid layer.

    Inputs:
        - `input`: the input Tensor to invert ([batch, channel, width, height])
    """

    def __init__(self, levels, mode='avg'):
        super(Spp3D, self).__init__()
        self.levels = levels
        self.mode = mode

    def forward(self, x):
        out = None
        for n in self.levels:
            d_r, w_r, h_r = map(lambda s: math.ceil(s / n), x.size()[2:])  # Receptive Field Size
            s_d, s_w, s_h = map(lambda s: math.floor(s / n), x.size()[2:])  # Stride
            if self.mode == 'max':
                pool = nn.MaxPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            elif self.mode == 'avg':
                pool = nn.AvgPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            else:
                raise RuntimeError("Unknown pooling type: %s, please use \"max\" or \"avg\".")
            y = pool(x)
            if out is None:
                out = y.view(y.size()[0], -1)
            else:
                out = torch.cat((out, y.view(y.size()[0], -1)), 1)
        return out

    def get_output_size(self, filters):
        out = 0
        for level in self.levels:
            out += filters * level * level * level
        return out


model = MC3_SPP()
flops, params = get_model_complexity_info(model, (3, 32, 256, 256), as_strings=True, print_per_layer_stat=False)
print("%s |%s |%s" % ('MC3_SPP', flops, params))
print('Model total # params:', count_params(model))

**Comment by 15762260991** [comment]
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from torchvision.models.video import mc3_18
from ptflops import get_model_complexity_info
from count_params import import_class, count_params

class MC3_SPP(nn.Module):
    def __init__(self, num_classes=10):
        super(MC3_SPP, self).__init__()

        self.mc3 = mc3_18(pretrained=False)
        
        self.mc3.pool = nn.Identity()
        self.mc3.fc = nn.Identity()
        self.mc3.avgpool = nn.Identity()
        
        self.pool3 = Spp3D([1, 2, 4], mode='avg')
        self.dropout1 = nn.Dropout3d(0.3)
        self.fc1 = nn.Linear(37376, 512) #32
        self.dropout2 = nn.Dropout3d(0.1)
        self.fc2 = nn.Linear(512, num_classes)


    def forward(self, x):
        features = self.mc3.stem(x)
        features = self.mc3.layer1(features)
        features = self.mc3.layer2(features)
        features = self.mc3.layer3(features)
        features = self.mc3.layer4(features)
        features = self.pool3(features)  # SPP max
        features = self.dropout1(features)
        features = torch.flatten(features, 1)  # Flatten tensor
        #print(features.shape)
        features = F.relu(self.fc1(features))  # First fully connected layer
        features = self.dropout2(features)
        features = self.fc2(features)
 

        return features


class Spp3D(nn.Module):
    """
    Args:
        levels (tuple): Length of side in the pooling results of each pyramid layer.

    Inputs:
        - `input`: the input Tensor to invert ([batch, channel, width, height])
    """

    def __init__(self, levels, mode='avg'):
        super(Spp3D, self).__init__()
        self.levels = levels
        self.mode = mode

    def forward(self, x):
        out = None
        for n in self.levels:
            d_r, w_r, h_r = map(lambda s: math.ceil(s / n), x.size()[2:])  # Receptive Field Size
            s_d, s_w, s_h = map(lambda s: math.floor(s / n), x.size()[2:])  # Stride
            if self.mode == 'max':
                pool = nn.MaxPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            elif self.mode == 'avg':
                pool = nn.AvgPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            else:
                raise RuntimeError("Unknown pooling type: %s, please use \"max\" or \"avg\".")
            y = pool(x)
            if out is None:
                out = y.view(y.size()[0], -1)
            else:
                out = torch.cat((out, y.view(y.size()[0], -1)), 1)
        return out

    def get_output_size(self, filters):
        out = 0
        for level in self.levels:
            out += filters * level * level * level
        return out


model = MC3_SPP()
flops, params = get_model_complexity_info(model, (3, 32, 256, 256), as_strings=True, print_per_layer_stat=False)
print("%s |%s |%s" % ('MC3_SPP', flops, params))
print('Model total # params:', count_params(model))

**Comment by 15762260991** [comment]
class MC3_SPP(nn.Module):
    def __init__(self, num_classes=10):
        super(MC3_SPP, self).__init__()

        self.mc3 = mc3_18(pretrained=False)
        
        self.mc3.pool = nn.Identity()
        self.mc3.fc = nn.Identity()
        self.mc3.avgpool = nn.Identity()
        
        self.pool3 = Spp3D([1, 2, 4], mode='avg')
        self.dropout1 = nn.Dropout3d(0.3)
        self.fc1 = nn.Linear(37376, 512) #32
        self.dropout2 = nn.Dropout3d(0.1)
        self.fc2 = nn.Linear(512, num_classes)


    def forward(self, x):
        features = self.mc3.stem(x)
        features = self.mc3.layer1(features)
        features = self.mc3.layer2(features)
        features = self.mc3.layer3(features)
        features = self.mc3.layer4(features)
        features = self.pool3(features)  # SPP max
        features = self.dropout1(features)
        features = torch.flatten(features, 1)  # Flatten tensor
        #print(features.shape)
        features = F.relu(self.fc1(features))  # First fully connected layer
        features = self.dropout2(features)
        features = self.fc2(features)
 

        return features


class Spp3D(nn.Module):
    """
    Args:
        levels (tuple): Length of side in the pooling results of each pyramid layer.

    Inputs:
        - `input`: the input Tensor to invert ([batch, channel, width, height])
    """

    def __init__(self, levels, mode='avg'):
        super(Spp3D, self).__init__()
        self.levels = levels
        self.mode = mode

    def forward(self, x):
        out = None
        for n in self.levels:
            d_r, w_r, h_r = map(lambda s: math.ceil(s / n), x.size()[2:])  # Receptive Field Size
            s_d, s_w, s_h = map(lambda s: math.floor(s / n), x.size()[2:])  # Stride
            if self.mode == 'max':
                pool = nn.MaxPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            elif self.mode == 'avg':
                pool = nn.AvgPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
            else:
                raise RuntimeError("Unknown pooling type: %s, please use \"max\" or \"avg\".")
            y = pool(x)
            if out is None:
                out = y.view(y.size()[0], -1)
            else:
                out = torch.cat((out, y.view(y.size()[0], -1)), 1)
        return out

    def get_output_size(self, filters):
        out = 0
        for level in self.levels:
            out += filters * level * level * level
        return out

**Comment by 15762260991** [comment]
> class MC3_SPP(nn.Module): def **init**(self, num_classes=10): super(MC3_SPP, self).**init**()
> 
> ```
>     self.mc3 = mc3_18(pretrained=False)
>     
>     self.mc3.pool = nn.Identity()
>     self.mc3.fc = nn.Identity()
>     self.mc3.avgpool = nn.Identity()
>     
>     self.pool3 = Spp3D([1, 2, 4], mode='avg')
>     self.dropout1 = nn.Dropout3d(0.3)
>     self.fc1 = nn.Linear(37376, 512) #32
>     self.dropout2 = nn.Dropout3d(0.1)
>     self.fc2 = nn.Linear(512, num_classes)
> 
> 
> def forward(self, x):
>     features = self.mc3.stem(x)
>     features = self.mc3.layer1(features)
>     features = self.mc3.layer2(features)
>     features = self.mc3.layer3(features)
>     features = self.mc3.layer4(features)
>     features = self.pool3(features)  # SPP max
>     features = self.dropout1(features)
>     features = torch.flatten(features, 1)  # Flatten tensor
>     #print(features.shape)
>     features = F.relu(self.fc1(features))  # First fully connected layer
>     features = self.dropout2(features)
>     features = self.fc2(features)
> 
> 
>     return features
> ```
> 
> class Spp3D(nn.Module): """ Args: levels (tuple): Length of side in the pooling results of each pyramid layer.
> 
> ```
> Inputs:
>     - `input`: the input Tensor to invert ([batch, channel, width, height])
> """
> 
> def __init__(self, levels, mode='avg'):
>     super(Spp3D, self).__init__()
>     self.levels = levels
>     self.mode = mode
> 
> def forward(self, x):
>     out = None
>     for n in self.levels:
>         d_r, w_r, h_r = map(lambda s: math.ceil(s / n), x.size()[2:])  # Receptive Field Size
>         s_d, s_w, s_h = map(lambda s: math.floor(s / n), x.size()[2:])  # Stride
>         if self.mode == 'max':
>             pool = nn.MaxPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
>         elif self.mode == 'avg':
>             pool = nn.AvgPool3d(kernel_size=(d_r, w_r, h_r), stride=(s_d, s_w, s_h))
>         else:
>             raise RuntimeError("Unknown pooling type: %s, please use \"max\" or \"avg\".")
>         y = pool(x)
>         if out is None:
>             out = y.view(y.size()[0], -1)
>         else:
>             out = torch.cat((out, y.view(y.size()[0], -1)), 1)
>     return out
> 
> def get_output_size(self, filters):
>     out = 0
>     for level in self.levels:
>         out += filters * level * level * level
>     return out
> ```

This is my code, I add SPP after 3D CNN, please don't hesitate to point out the mistakes, I'd appreciate it! @marciniega

**Comment by 15762260991** [comment]
Please do not hesitate to guide me! @marciniega
